2018-11-15 21:18:59,433 : INFO : Machine : Mission Pinball Framework Core Engine v0.50.21
2018-11-15 21:18:59,433 : INFO : Machine : Command line arguments: {'force_platform': None, 'text_ui': True, 'configfile': ['config.yaml'], 'pause': False, 'bcp': False, 'consoleloglevel': 20, 'loglevel': 15, 'logfile': 'logs/2018-11-15-21-18-59-mpf-Sean-Pauls-MacBook-Pro.local.log', 'syslog_address': None, 'force_assets_load': False, 'no_load_cache': False, 'create_config_cache': True, 'mpfconfigfile': '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mpf/mpfconfig.yaml', 'mc_file_name': None, 'production': False}
2018-11-15 21:18:59,433 : INFO : Machine : MPF path: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mpf
2018-11-15 21:18:59,433 : INFO : Machine : Machine path: /Users/seanpaulfenton/src/mpf/tutorials
2018-11-15 21:18:59,433 : INFO : Machine : Platform: darwin
2018-11-15 21:18:59,433 : INFO : Machine : Python executable location: /Library/Frameworks/Python.framework/Versions/3.5/bin/python3
2018-11-15 21:18:59,433 : INFO : Machine : Python version: 3.5.2 (64-bit)
2018-11-15 21:18:59,737 : INFO : Machine : Machine config file #1: config.yaml
2018-11-15 21:18:59,740 : WARNING : ConfigProcessor : Config file in cache changed: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mpf/mpfconfig.yaml
2018-11-15 21:18:59,740 : INFO : ConfigProcessor : Loading config from file /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mpf/mpfconfig.yaml.
2018-11-15 21:18:59,805 : INFO : ConfigProcessor : Loading config: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mpf/mpfconfig.yaml
2018-11-15 21:18:59,806 : INFO : ConfigProcessor : Loading config from file /Users/seanpaulfenton/src/mpf/tutorials/config/config.yaml.
2018-11-15 21:18:59,810 : INFO : ConfigProcessor : Config file cache created: /var/folders/nx/hjkv90px0cg9f03hrdxkbb700000gn/T/3ec8cc6c3dd126689f251dcfb87d3ebc.mpf_cache
2018-11-15 21:18:59,810 : INFO : Machine : Initialise MPF.
2018-11-15 21:18:59,954 : ERROR : Machine : ERROR: Failed to initialise MPF: curs_set() returned ERR
2018-11-15 21:18:59,956 : INFO : Machine : Starting the main run loop.
2018-11-15 21:19:00,121 : ERROR : root : Event loop is closed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mpf/commands/game.py", line 208, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mpf/core/machine.py", line 664, in run
    self._run_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mpf/core/machine.py", line 702, in _run_loop
    self.clock.run(self.stop_future)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mpf/core/clock.py", line 82, in run
    self.loop.run_until_complete(stop_future)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 364, in run_until_complete
    self._check_closed()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
